image: node:24-alpine

variables:
  STAGING_DIR: /srv/gitlab-ce-pages/staging
  BUILD_DIR: $STAGING_DIR/$CI_PIPELINE_ID/$CI_COMMIT_REF_NAME/$CI_PROJECT_PATH
  DEPLOY_DIR: $STAGING_DIR/$CI_JOB_ID/$CI_COMMIT_REF_NAME
  SITE_URL: https://www.example.edu
  BASE_PATH: /$CI_PROJECT_PATH

page-build:
  tags:
    - Pages
  stage: build
  before_script:
    - apk add --no-cache git
    - corepack enable
    - pnpm install --frozen-lockfile
  script:
    - pnpm build
    - mkdir -p $BUILD_DIR
    - cp -r dist/* $BUILD_DIR/
  only:
    - main

page-deploy:
  tags:
    - Pages
  stage: deploy
  script:
    - mkdir -p $DEPLOY_DIR/`dirname $CI_PROJECT_PATH`
    - mv $BUILD_DIR $DEPLOY_DIR/$CI_PROJECT_PATH
    - rm -rf $STAGING_DIR/$CI_PIPELINE_ID
  only:
    - main
